CREATE TABLE crm_pipelines(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id),organization_id uuid NOT NULL REFERENCES organizations(id),activity text NOT NULL,name text NOT NULL,stages jsonb NOT NULL CHECK(jsonb_typeof(stages)='array'),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL);
CREATE INDEX crm_pipelines_tenant_organization_idx ON crm_pipelines(tenant_id,organization_id,active);
CREATE TABLE crm_opportunities(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id),organization_id uuid NOT NULL REFERENCES organizations(id),site_id uuid NOT NULL REFERENCES sites(id),pipeline_id uuid NOT NULL REFERENCES crm_pipelines(id),stage_key text NOT NULL,kind text NOT NULL,title text NOT NULL,customer_id uuid NOT NULL REFERENCES customers(id),asset_id uuid REFERENCES assets(id),channel text NOT NULL,acquisition_owner_organization_id uuid REFERENCES organizations(id),assigned_to uuid,estimated_value_cents integer CHECK(estimated_value_cents IS NULL OR estimated_value_cents>=0),currency char(3) NOT NULL,status text NOT NULL CHECK(status IN('open','won','lost','cancelled')),lost_reason text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object'),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX crm_opportunities_pipeline_idx ON crm_opportunities(tenant_id,pipeline_id,stage_key,status);
CREATE INDEX crm_opportunities_customer_idx ON crm_opportunities(tenant_id,customer_id,updated_at DESC);
CREATE TABLE crm_tasks(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id),opportunity_id uuid NOT NULL REFERENCES crm_opportunities(id),assigned_to uuid,type text NOT NULL CHECK(type IN('call','email','sms','appointment','document','custom')),title text NOT NULL,due_at timestamptz NOT NULL,status text NOT NULL CHECK(status IN('open','completed','cancelled')),automation_key text,created_at timestamptz NOT NULL);
CREATE INDEX crm_tasks_due_idx ON crm_tasks(tenant_id,status,due_at);
CREATE UNIQUE INDEX crm_tasks_automation_once_idx ON crm_tasks(tenant_id,opportunity_id,automation_key) WHERE automation_key IS NOT NULL;
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['crm_pipelines','crm_opportunities','crm_tasks'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=current_setting(''app.tenant_id'',true)::uuid) WITH CHECK (tenant_id=current_setting(''app.tenant_id'',true)::uuid)',n);END LOOP;END $$;
