-- Tenant-scoped relations must carry the tenant on both sides of every foreign key.
DO $$
DECLARE target text;
BEGIN
  FOREACH target IN ARRAY ARRAY[
    'organizations','sites','customers','assets','service_offerings','availability_slots','bookings',
    'passports','passport_entries','asset_deadlines','documents','consents','document_share_grants',
    'crm_pipelines','crm_opportunities','notification_templates','notifications','workflow_definitions',
    'workflow_instances','workflow_work_items','quotes','sales_orders','invoices','payments','work_orders','parts',
    'passport_qr_grants','reminders','crm_tasks','consents','document_share_grants',
    'disclosure_logs','payment_refunds','bank_transactions','stock_reservations','purchase_orders'
  ] LOOP
    EXECUTE format('CREATE UNIQUE INDEX IF NOT EXISTS %I ON %I (tenant_id,id)', target || '_tenant_id_id_uidx', target);
  END LOOP;
END $$;

ALTER TABLE sites DROP CONSTRAINT sites_organization_id_fkey, ADD CONSTRAINT sites_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE memberships DROP CONSTRAINT memberships_organization_id_fkey, ADD CONSTRAINT memberships_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE customers DROP CONSTRAINT customers_acquisition_owner_organization_id_fkey, ADD CONSTRAINT customers_tenant_acquisition_owner_fk FOREIGN KEY(tenant_id,acquisition_owner_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE assets DROP CONSTRAINT assets_owner_customer_id_fkey, ADD CONSTRAINT assets_tenant_owner_fk FOREIGN KEY(tenant_id,owner_customer_id) REFERENCES customers(tenant_id,id);
ALTER TABLE service_offerings DROP CONSTRAINT service_offerings_organization_id_fkey, DROP CONSTRAINT service_offerings_site_id_fkey, ADD CONSTRAINT offerings_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT offerings_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id);
ALTER TABLE availability_slots DROP CONSTRAINT availability_slots_offering_id_fkey, DROP CONSTRAINT availability_slots_site_id_fkey, ADD CONSTRAINT slots_tenant_offering_fk FOREIGN KEY(tenant_id,offering_id) REFERENCES service_offerings(tenant_id,id), ADD CONSTRAINT slots_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id);
ALTER TABLE bookings DROP CONSTRAINT bookings_organization_id_fkey, DROP CONSTRAINT bookings_site_id_fkey, DROP CONSTRAINT bookings_offering_id_fkey, DROP CONSTRAINT bookings_slot_id_fkey, DROP CONSTRAINT bookings_customer_id_fkey, DROP CONSTRAINT bookings_asset_id_fkey, DROP CONSTRAINT bookings_acquisition_owner_organization_id_fkey, ADD CONSTRAINT bookings_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT bookings_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT bookings_tenant_offering_fk FOREIGN KEY(tenant_id,offering_id) REFERENCES service_offerings(tenant_id,id), ADD CONSTRAINT bookings_tenant_slot_fk FOREIGN KEY(tenant_id,slot_id) REFERENCES availability_slots(tenant_id,id), ADD CONSTRAINT bookings_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT bookings_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), ADD CONSTRAINT bookings_tenant_acquisition_owner_fk FOREIGN KEY(tenant_id,acquisition_owner_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE passports DROP CONSTRAINT passports_asset_id_fkey, DROP CONSTRAINT passports_owner_customer_id_fkey, ADD CONSTRAINT passports_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), ADD CONSTRAINT passports_tenant_owner_fk FOREIGN KEY(tenant_id,owner_customer_id) REFERENCES customers(tenant_id,id);
ALTER TABLE documents DROP CONSTRAINT documents_owner_customer_id_fkey, DROP CONSTRAINT documents_asset_id_fkey, DROP CONSTRAINT documents_passport_id_fkey, ADD CONSTRAINT documents_tenant_owner_fk FOREIGN KEY(tenant_id,owner_customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT documents_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), ADD CONSTRAINT documents_tenant_passport_fk FOREIGN KEY(tenant_id,passport_id) REFERENCES passports(tenant_id,id);
ALTER TABLE crm_opportunities DROP CONSTRAINT crm_opportunities_organization_id_fkey, DROP CONSTRAINT crm_opportunities_site_id_fkey, DROP CONSTRAINT crm_opportunities_pipeline_id_fkey, DROP CONSTRAINT crm_opportunities_customer_id_fkey, DROP CONSTRAINT crm_opportunities_asset_id_fkey, ADD CONSTRAINT crm_opportunities_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT crm_opportunities_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT crm_opportunities_tenant_pipeline_fk FOREIGN KEY(tenant_id,pipeline_id) REFERENCES crm_pipelines(tenant_id,id), ADD CONSTRAINT crm_opportunities_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT crm_opportunities_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id);
ALTER TABLE quotes DROP CONSTRAINT quotes_organization_id_fkey, DROP CONSTRAINT quotes_site_id_fkey, DROP CONSTRAINT quotes_customer_id_fkey, DROP CONSTRAINT quotes_asset_id_fkey, ADD CONSTRAINT quotes_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT quotes_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT quotes_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT quotes_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id);
ALTER TABLE work_orders DROP CONSTRAINT work_orders_organization_id_fkey, DROP CONSTRAINT work_orders_site_id_fkey, DROP CONSTRAINT work_orders_customer_id_fkey, DROP CONSTRAINT work_orders_asset_id_fkey, ADD CONSTRAINT work_orders_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT work_orders_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT work_orders_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT work_orders_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id);

ALTER TABLE passport_entries DROP CONSTRAINT passport_entries_passport_id_fkey, DROP CONSTRAINT passport_entries_asset_id_fkey, DROP CONSTRAINT passport_entries_provider_organization_id_fkey, ADD CONSTRAINT passport_entries_tenant_passport_fk FOREIGN KEY(tenant_id,passport_id) REFERENCES passports(tenant_id,id), ADD CONSTRAINT passport_entries_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), ADD CONSTRAINT passport_entries_tenant_provider_fk FOREIGN KEY(tenant_id,provider_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE asset_deadlines DROP CONSTRAINT asset_deadlines_passport_id_fkey, DROP CONSTRAINT asset_deadlines_asset_id_fkey, DROP CONSTRAINT asset_deadlines_source_entry_id_fkey, ADD CONSTRAINT asset_deadlines_tenant_passport_fk FOREIGN KEY(tenant_id,passport_id) REFERENCES passports(tenant_id,id), ADD CONSTRAINT asset_deadlines_tenant_asset_fk FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), ADD CONSTRAINT asset_deadlines_tenant_source_fk FOREIGN KEY(tenant_id,source_entry_id) REFERENCES passport_entries(tenant_id,id);
ALTER TABLE passport_qr_grants DROP CONSTRAINT passport_qr_grants_passport_id_fkey, ADD CONSTRAINT passport_qr_grants_tenant_passport_fk FOREIGN KEY(tenant_id,passport_id) REFERENCES passports(tenant_id,id);
ALTER TABLE reminders DROP CONSTRAINT reminders_deadline_id_fkey, DROP CONSTRAINT reminders_customer_id_fkey, ADD CONSTRAINT reminders_tenant_deadline_fk FOREIGN KEY(tenant_id,deadline_id) REFERENCES asset_deadlines(tenant_id,id), ADD CONSTRAINT reminders_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id);

ALTER TABLE consents DROP CONSTRAINT consents_customer_id_fkey, DROP CONSTRAINT consents_grantee_organization_id_fkey, ADD CONSTRAINT consents_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT consents_tenant_grantee_fk FOREIGN KEY(tenant_id,grantee_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE document_share_grants DROP CONSTRAINT document_share_grants_document_id_fkey, DROP CONSTRAINT document_share_grants_issued_to_customer_id_fkey, DROP CONSTRAINT document_share_grants_issued_to_organization_id_fkey, ADD CONSTRAINT document_shares_tenant_document_fk FOREIGN KEY(tenant_id,document_id) REFERENCES documents(tenant_id,id), ADD CONSTRAINT document_shares_tenant_customer_fk FOREIGN KEY(tenant_id,issued_to_customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT document_shares_tenant_organization_fk FOREIGN KEY(tenant_id,issued_to_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE disclosure_logs DROP CONSTRAINT disclosure_logs_document_id_fkey, DROP CONSTRAINT disclosure_logs_consent_id_fkey, ADD CONSTRAINT disclosure_logs_tenant_document_fk FOREIGN KEY(tenant_id,document_id) REFERENCES documents(tenant_id,id), ADD CONSTRAINT disclosure_logs_tenant_consent_fk FOREIGN KEY(tenant_id,consent_id) REFERENCES consents(tenant_id,id);

ALTER TABLE crm_pipelines DROP CONSTRAINT crm_pipelines_organization_id_fkey, ADD CONSTRAINT crm_pipelines_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE crm_opportunities DROP CONSTRAINT crm_opportunities_acquisition_owner_organization_id_fkey, ADD CONSTRAINT crm_opportunities_tenant_acquisition_owner_fk FOREIGN KEY(tenant_id,acquisition_owner_organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE crm_tasks DROP CONSTRAINT crm_tasks_opportunity_id_fkey, ADD CONSTRAINT crm_tasks_tenant_opportunity_fk FOREIGN KEY(tenant_id,opportunity_id) REFERENCES crm_opportunities(tenant_id,id);

ALTER TABLE notification_templates DROP CONSTRAINT notification_templates_organization_id_fkey, ADD CONSTRAINT notification_templates_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE notification_preferences DROP CONSTRAINT notification_preferences_customer_id_fkey, ADD CONSTRAINT notification_preferences_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id);
ALTER TABLE notifications DROP CONSTRAINT notifications_organization_id_fkey, DROP CONSTRAINT notifications_customer_id_fkey, DROP CONSTRAINT notifications_template_id_fkey, ADD CONSTRAINT notifications_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT notifications_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT notifications_tenant_template_fk FOREIGN KEY(tenant_id,template_id) REFERENCES notification_templates(tenant_id,id);

ALTER TABLE workflow_definitions DROP CONSTRAINT workflow_definitions_organization_id_fkey, ADD CONSTRAINT workflow_definitions_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE workflow_instances DROP CONSTRAINT workflow_instances_organization_id_fkey, DROP CONSTRAINT workflow_instances_site_id_fkey, DROP CONSTRAINT workflow_instances_definition_id_fkey, ADD CONSTRAINT workflow_instances_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT workflow_instances_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT workflow_instances_tenant_definition_fk FOREIGN KEY(tenant_id,definition_id) REFERENCES workflow_definitions(tenant_id,id);
ALTER TABLE workflow_work_items DROP CONSTRAINT workflow_work_items_instance_id_fkey, ADD CONSTRAINT workflow_work_items_tenant_instance_fk FOREIGN KEY(tenant_id,instance_id) REFERENCES workflow_instances(tenant_id,id);

ALTER TABLE quotes DROP CONSTRAINT quotes_opportunity_id_fkey, DROP CONSTRAINT quotes_accepted_by_customer_id_fkey, ADD CONSTRAINT quotes_tenant_opportunity_fk FOREIGN KEY(tenant_id,opportunity_id) REFERENCES crm_opportunities(tenant_id,id), ADD CONSTRAINT quotes_tenant_accepting_customer_fk FOREIGN KEY(tenant_id,accepted_by_customer_id) REFERENCES customers(tenant_id,id);
ALTER TABLE sales_orders DROP CONSTRAINT sales_orders_organization_id_fkey, DROP CONSTRAINT sales_orders_site_id_fkey, DROP CONSTRAINT sales_orders_customer_id_fkey, DROP CONSTRAINT sales_orders_quote_id_fkey, ADD CONSTRAINT sales_orders_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT sales_orders_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT sales_orders_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT sales_orders_tenant_quote_fk FOREIGN KEY(tenant_id,quote_id) REFERENCES quotes(tenant_id,id);
ALTER TABLE invoices DROP CONSTRAINT invoices_organization_id_fkey, DROP CONSTRAINT invoices_site_id_fkey, DROP CONSTRAINT invoices_customer_id_fkey, DROP CONSTRAINT invoices_order_id_fkey, ADD CONSTRAINT invoices_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT invoices_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT invoices_tenant_customer_fk FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id), ADD CONSTRAINT invoices_tenant_order_fk FOREIGN KEY(tenant_id,order_id) REFERENCES sales_orders(tenant_id,id);
ALTER TABLE payments DROP CONSTRAINT payments_invoice_id_fkey, ADD CONSTRAINT payments_tenant_invoice_fk FOREIGN KEY(tenant_id,invoice_id) REFERENCES invoices(tenant_id,id);
ALTER TABLE payment_refunds DROP CONSTRAINT payment_refunds_payment_id_fkey, ADD CONSTRAINT payment_refunds_tenant_payment_fk FOREIGN KEY(tenant_id,payment_id) REFERENCES payments(tenant_id,id);
ALTER TABLE bank_transactions DROP CONSTRAINT bank_transactions_matched_payment_id_fkey, ADD CONSTRAINT bank_transactions_tenant_payment_fk FOREIGN KEY(tenant_id,matched_payment_id) REFERENCES payments(tenant_id,id);

ALTER TABLE work_orders DROP CONSTRAINT work_orders_booking_id_fkey, DROP CONSTRAINT work_orders_quote_id_fkey, ADD CONSTRAINT work_orders_tenant_booking_fk FOREIGN KEY(tenant_id,booking_id) REFERENCES bookings(tenant_id,id), ADD CONSTRAINT work_orders_tenant_quote_fk FOREIGN KEY(tenant_id,quote_id) REFERENCES quotes(tenant_id,id);
ALTER TABLE parts DROP CONSTRAINT parts_organization_id_fkey, ADD CONSTRAINT parts_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE stock_positions DROP CONSTRAINT stock_positions_site_id_fkey, DROP CONSTRAINT stock_positions_part_id_fkey, ADD CONSTRAINT stock_positions_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT stock_positions_tenant_part_fk FOREIGN KEY(tenant_id,part_id) REFERENCES parts(tenant_id,id);
ALTER TABLE stock_reservations DROP CONSTRAINT stock_reservations_site_id_fkey, DROP CONSTRAINT stock_reservations_part_id_fkey, DROP CONSTRAINT stock_reservations_work_order_id_fkey, ADD CONSTRAINT stock_reservations_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id), ADD CONSTRAINT stock_reservations_tenant_part_fk FOREIGN KEY(tenant_id,part_id) REFERENCES parts(tenant_id,id), ADD CONSTRAINT stock_reservations_tenant_work_order_fk FOREIGN KEY(tenant_id,work_order_id) REFERENCES work_orders(tenant_id,id);
ALTER TABLE purchase_orders DROP CONSTRAINT purchase_orders_organization_id_fkey, DROP CONSTRAINT purchase_orders_site_id_fkey, ADD CONSTRAINT purchase_orders_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id), ADD CONSTRAINT purchase_orders_tenant_site_fk FOREIGN KEY(tenant_id,site_id) REFERENCES sites(tenant_id,id);

ALTER TABLE quote_sequences DROP CONSTRAINT quote_sequences_organization_id_fkey, ADD CONSTRAINT quote_sequences_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE finance_sequences DROP CONSTRAINT finance_sequences_organization_id_fkey, ADD CONSTRAINT finance_sequences_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE workshop_sequences DROP CONSTRAINT workshop_sequences_organization_id_fkey, ADD CONSTRAINT workshop_sequences_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
ALTER TABLE purchase_sequences DROP CONSTRAINT purchase_sequences_organization_id_fkey, ADD CONSTRAINT purchase_sequences_tenant_organization_fk FOREIGN KEY(tenant_id,organization_id) REFERENCES organizations(tenant_id,id);
