import type { Pool,PoolClient } from "pg";
import { DomainError } from "../../packages/core/src/errors.ts";
import type { EntityId,TenantId } from "../../packages/core/src/identity.ts";
import type { VehicleCommerceRepository,VehicleDeliveryProps,VehicleMediaProps,VehicleOwnershipTransferProps,VehiclePreparationCheckProps,VehiclePublicationProps,VehicleSaleProps,VehicleStockItemProps } from "../../packages/vehicle-commerce/src/vehicle-commerce.ts";

export class PostgresVehicleCommerceRepository implements VehicleCommerceRepository {
  private readonly pool:Pool;
  private readonly transaction:PoolClient|undefined;
  constructor(pool:Pool,transaction:PoolClient|undefined=undefined){this.pool=pool;this.transaction=transaction;}
  private async tx<T>(tenantId:TenantId,operation:(client:PoolClient)=>Promise<T>):Promise<T>{if(this.transaction)return operation(this.transaction);const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenantId]);const result=await operation(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async assetExists(tenantId:TenantId,assetId:EntityId){return this.tx(tenantId,async client=>(await client.query("SELECT 1 FROM assets WHERE tenant_id=$1 AND id=$2",[tenantId,assetId])).rowCount===1);}
  async siteBelongsToOrganization(tenantId:TenantId,organizationId:EntityId,siteId:EntityId){return this.tx(tenantId,async client=>(await client.query("SELECT 1 FROM sites WHERE tenant_id=$1 AND organization_id=$2 AND id=$3",[tenantId,organizationId,siteId])).rowCount===1);}
  async customerExists(tenantId:TenantId,customerId:EntityId){return this.tx(tenantId,async client=>(await client.query("SELECT 1 FROM customers WHERE tenant_id=$1 AND id=$2",[tenantId,customerId])).rowCount===1);}
  async findSale(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>{const result=await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",buyer_customer_id AS "buyerCustomerId",sale_price_cents AS "salePriceCents",acquisition_cost_cents AS "acquisitionCostCents",gross_margin_cents AS "grossMarginCents",sold_by AS "soldBy",sold_at AS "soldAt" FROM vehicle_sales WHERE tenant_id=$1 AND stock_item_id=$2`,[tenantId,stockItemId]);return(result.rows[0] as VehicleSaleProps|undefined)??null;});}
  async findDelivery(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>{const result=await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",sale_id AS "saleId",status,planned_at AS "plannedAt",handover_odometer_km AS "handoverOdometerKm",notes,scheduled_by AS "scheduledBy",completed_by AS "completedBy",completed_at AS "completedAt",created_at AS "createdAt" FROM vehicle_deliveries WHERE tenant_id=$1 AND stock_item_id=$2`,[tenantId,stockItemId]);return(result.rows[0] as VehicleDeliveryProps|undefined)??null;});}
  async assetOwnerCustomerId(tenantId:TenantId,assetId:EntityId){return this.tx(tenantId,async client=>{const result=await client.query("SELECT owner_customer_id FROM assets WHERE tenant_id=$1 AND id=$2",[tenantId,assetId]);return(result.rows[0]?.owner_customer_id as EntityId|undefined)??null;});}
  async documentsBelongToAsset(tenantId:TenantId,assetId:EntityId,documentIds:readonly EntityId[]){return this.tx(tenantId,async client=>{const result=await client.query("SELECT count(*)::int AS count FROM documents WHERE tenant_id=$1 AND asset_id=$2 AND id=ANY($3::uuid[])",[tenantId,assetId,documentIds]);return result.rows[0].count===documentIds.length;});}
  async saveStockItem(value:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,client=>client.query(`INSERT INTO vehicle_stock_items(id,tenant_id,organization_id,site_id,asset_id,acquisition_mode,acquisition_cost_cents,asking_price_cents,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET asking_price_cents=EXCLUDED.asking_price_cents,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`,[value.id,value.tenantId,value.organizationId,value.siteId,value.assetId,value.acquisitionMode,value.acquisitionCostCents,value.askingPriceCents??null,value.status,value.createdBy,value.createdAt,value.updatedAt]).then(()=>undefined));}
  async findStockItem(tenantId:TenantId,id:EntityId){return this.tx(tenantId,async client=>{const result=await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",asset_id AS "assetId",acquisition_mode AS "acquisitionMode",acquisition_cost_cents AS "acquisitionCostCents",asking_price_cents AS "askingPriceCents",status,created_by AS "createdBy",created_at AS "createdAt",updated_at AS "updatedAt" FROM vehicle_stock_items WHERE tenant_id=$1 AND id=$2`,[tenantId,id]);return(result.rows[0] as VehicleStockItemProps|undefined)??null;});}
  async listPublications(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>(await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",channel,asking_price_cents AS "askingPriceCents",status,published_by AS "publishedBy",published_at AS "publishedAt" FROM vehicle_publications WHERE tenant_id=$1 AND stock_item_id=$2`,[tenantId,stockItemId])).rows as VehiclePublicationProps[]);}
  async savePreparationCheck(value:Readonly<VehiclePreparationCheckProps>){await this.tx(value.tenantId,client=>client.query(`INSERT INTO vehicle_preparation_checks(id,tenant_id,organization_id,site_id,stock_item_id,label,required,completed_by,completed_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET completed_by=EXCLUDED.completed_by,completed_at=EXCLUDED.completed_at`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.label,value.required,value.completedBy??null,value.completedAt??null,value.createdAt]).then(()=>undefined));}
  async listPreparationChecks(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>(await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",label,required,completed_by AS "completedBy",completed_at AS "completedAt",created_at AS "createdAt" FROM vehicle_preparation_checks WHERE tenant_id=$1 AND stock_item_id=$2 ORDER BY created_at`,[tenantId,stockItemId])).rows as VehiclePreparationCheckProps[]);}
  async saveMedia(value:Readonly<VehicleMediaProps>){await this.tx(value.tenantId,client=>client.query(`INSERT INTO vehicle_media(id,tenant_id,organization_id,site_id,stock_item_id,kind,storage_key,position,is_primary,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.kind,value.storageKey,value.position,value.primary,value.createdBy,value.createdAt]).then(()=>undefined));}
  async listMedia(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>(await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",kind,storage_key AS "storageKey",position,is_primary AS primary,created_by AS "createdBy",created_at AS "createdAt" FROM vehicle_media WHERE tenant_id=$1 AND stock_item_id=$2 ORDER BY position`,[tenantId,stockItemId])).rows as VehicleMediaProps[]);}
  async withStockItemLock<T>(tenantId:TenantId,id:EntityId,operation:(repository:VehicleCommerceRepository)=>Promise<T>):Promise<T>{return this.tx(tenantId,async client=>{await client.query("SELECT id FROM vehicle_stock_items WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[tenantId,id]);return operation(new PostgresVehicleCommerceRepository(this.pool,client));});}
  async publish(value:Readonly<VehiclePublicationProps>,stockItem:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,async client=>{await client.query(`INSERT INTO vehicle_publications(id,tenant_id,organization_id,site_id,stock_item_id,channel,asking_price_cents,status,published_by,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.channel,value.askingPriceCents,value.status,value.publishedBy,value.publishedAt]);await client.query("UPDATE vehicle_stock_items SET status=$3,updated_at=$4 WHERE tenant_id=$1 AND id=$2",[stockItem.tenantId,stockItem.id,stockItem.status,stockItem.updatedAt]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_published.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,channel:value.channel}),value.publishedAt]);});}
  async markReady(stockItem:Readonly<VehicleStockItemProps>,readyBy:EntityId){await this.tx(stockItem.tenantId,async client=>{await client.query("UPDATE vehicle_stock_items SET asking_price_cents=$3,status='ready',updated_at=$4 WHERE tenant_id=$1 AND id=$2",[stockItem.tenantId,stockItem.id,stockItem.askingPriceCents,stockItem.updatedAt]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_ready.v1',$3,$4)`,[stockItem.tenantId,stockItem.id,JSON.stringify({organizationId:stockItem.organizationId,siteId:stockItem.siteId,readyBy}),stockItem.updatedAt]);});}
  async sell(value:Readonly<VehicleSaleProps>,stockItem:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,async client=>{await client.query(`INSERT INTO vehicle_sales(id,tenant_id,organization_id,site_id,stock_item_id,buyer_customer_id,sale_price_cents,acquisition_cost_cents,gross_margin_cents,sold_by,sold_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.buyerCustomerId,value.salePriceCents,value.acquisitionCostCents,value.grossMarginCents,value.soldBy,value.soldAt]);await client.query("UPDATE vehicle_stock_items SET status='sold',updated_at=$3 WHERE tenant_id=$1 AND id=$2",[stockItem.tenantId,stockItem.id,stockItem.updatedAt]);await client.query("UPDATE vehicle_publications SET status='withdrawn' WHERE tenant_id=$1 AND stock_item_id=$2 AND status='published'",[stockItem.tenantId,stockItem.id]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_sold.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,buyerCustomerId:value.buyerCustomerId,salePriceCents:value.salePriceCents,grossMarginCents:value.grossMarginCents}),value.soldAt]);});}
  async saveDelivery(value:Readonly<VehicleDeliveryProps>){await this.tx(value.tenantId,async client=>{await client.query(`INSERT INTO vehicle_deliveries(id,tenant_id,organization_id,site_id,stock_item_id,sale_id,status,planned_at,scheduled_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.saleId,value.status,value.plannedAt,value.scheduledBy,value.createdAt]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_delivery_scheduled.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,saleId:value.saleId,plannedAt:value.plannedAt}),value.createdAt]);});}
  async completeDelivery(value:Readonly<VehicleDeliveryProps>,stockItem:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,async client=>{await client.query(`UPDATE vehicle_deliveries SET status='completed',handover_odometer_km=$3,notes=$4,completed_by=$5,completed_at=$6 WHERE tenant_id=$1 AND id=$2 AND status='scheduled'`,[value.tenantId,value.id,value.handoverOdometerKm,value.notes??null,value.completedBy,value.completedAt]);await client.query("UPDATE vehicle_stock_items SET status='delivered',updated_at=$3 WHERE tenant_id=$1 AND id=$2",[stockItem.tenantId,stockItem.id,stockItem.updatedAt]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_delivered.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,saleId:value.saleId,handoverOdometerKm:value.handoverOdometerKm}),value.completedAt]);});}
  async transferOwnership(value:Readonly<VehicleOwnershipTransferProps>){await this.tx(value.tenantId,async client=>{const passport=await client.query("SELECT id FROM passports WHERE tenant_id=$1 AND asset_id=$2 FOR UPDATE",[value.tenantId,value.assetId]);const passportId=passport.rows[0]?.id as EntityId|undefined;if(!passportId)throw new DomainError("PASSPORT_NOT_FOUND","Passport was not found");await client.query(`INSERT INTO vehicle_ownership_transfers(id,tenant_id,organization_id,site_id,stock_item_id,sale_id,delivery_id,asset_id,previous_owner_customer_id,new_owner_customer_id,evidence_hash,transferred_by,transferred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.saleId,value.deliveryId,value.assetId,value.previousOwnerCustomerId,value.newOwnerCustomerId,value.evidenceHash,value.transferredBy,value.transferredAt]);for(const documentId of value.documentIds)await client.query("INSERT INTO vehicle_transfer_documents(tenant_id,transfer_id,document_id) VALUES($1,$2,$3)",[value.tenantId,value.id,documentId]);const assetUpdate=await client.query("UPDATE assets SET owner_customer_id=$3 WHERE tenant_id=$1 AND id=$2 AND owner_customer_id=$4",[value.tenantId,value.assetId,value.newOwnerCustomerId,value.previousOwnerCustomerId]);const passportUpdate=await client.query("UPDATE passports SET owner_customer_id=$3 WHERE tenant_id=$1 AND id=$2 AND owner_customer_id=$4",[value.tenantId,passportId,value.newOwnerCustomerId,value.previousOwnerCustomerId]);if(assetUpdate.rowCount!==1||passportUpdate.rowCount!==1)throw new DomainError("OWNERSHIP_CONFLICT","Asset ownership changed concurrently");await client.query(`INSERT INTO passport_entries(id,tenant_id,passport_id,asset_id,type,title,occurred_at,mileage,provider_organization_id,document_ids,visibility,evidence_hash,created_by,created_at) VALUES(gen_random_uuid(),$1,$2,$3,'ownership','Transfert de propriété',$4,NULL,$5,$6,'owner_only',$7,$8,$4)`,[value.tenantId,passportId,value.assetId,value.transferredAt,value.organizationId,value.documentIds,value.evidenceHash,value.transferredBy]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_ownership_transferred.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,assetId:value.assetId,previousOwnerCustomerId:value.previousOwnerCustomerId,newOwnerCustomerId:value.newOwnerCustomerId,documentIds:value.documentIds}),value.transferredAt]);});}
}
