import type { Pool,PoolClient } from "pg";
import type { EntityId,TenantId } from "../../packages/core/src/identity.ts";
import type { VehicleCommerceRepository,VehiclePublicationProps,VehicleStockItemProps } from "../../packages/vehicle-commerce/src/vehicle-commerce.ts";

export class PostgresVehicleCommerceRepository implements VehicleCommerceRepository {
  private readonly pool:Pool;
  private readonly transaction:PoolClient|undefined;
  constructor(pool:Pool,transaction:PoolClient|undefined=undefined){this.pool=pool;this.transaction=transaction;}
  private async tx<T>(tenantId:TenantId,operation:(client:PoolClient)=>Promise<T>):Promise<T>{if(this.transaction)return operation(this.transaction);const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenantId]);const result=await operation(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async assetExists(tenantId:TenantId,assetId:EntityId){return this.tx(tenantId,async client=>(await client.query("SELECT 1 FROM assets WHERE tenant_id=$1 AND id=$2",[tenantId,assetId])).rowCount===1);}
  async siteBelongsToOrganization(tenantId:TenantId,organizationId:EntityId,siteId:EntityId){return this.tx(tenantId,async client=>(await client.query("SELECT 1 FROM sites WHERE tenant_id=$1 AND organization_id=$2 AND id=$3",[tenantId,organizationId,siteId])).rowCount===1);}
  async saveStockItem(value:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,client=>client.query(`INSERT INTO vehicle_stock_items(id,tenant_id,organization_id,site_id,asset_id,acquisition_mode,acquisition_cost_cents,asking_price_cents,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET asking_price_cents=EXCLUDED.asking_price_cents,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`,[value.id,value.tenantId,value.organizationId,value.siteId,value.assetId,value.acquisitionMode,value.acquisitionCostCents,value.askingPriceCents??null,value.status,value.createdBy,value.createdAt,value.updatedAt]).then(()=>undefined));}
  async findStockItem(tenantId:TenantId,id:EntityId){return this.tx(tenantId,async client=>{const result=await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",asset_id AS "assetId",acquisition_mode AS "acquisitionMode",acquisition_cost_cents AS "acquisitionCostCents",asking_price_cents AS "askingPriceCents",status,created_by AS "createdBy",created_at AS "createdAt",updated_at AS "updatedAt" FROM vehicle_stock_items WHERE tenant_id=$1 AND id=$2`,[tenantId,id]);return(result.rows[0] as VehicleStockItemProps|undefined)??null;});}
  async listPublications(tenantId:TenantId,stockItemId:EntityId){return this.tx(tenantId,async client=>(await client.query(`SELECT id,tenant_id AS "tenantId",organization_id AS "organizationId",site_id AS "siteId",stock_item_id AS "stockItemId",channel,asking_price_cents AS "askingPriceCents",status,published_by AS "publishedBy",published_at AS "publishedAt" FROM vehicle_publications WHERE tenant_id=$1 AND stock_item_id=$2`,[tenantId,stockItemId])).rows as VehiclePublicationProps[]);}
  async withStockItemLock<T>(tenantId:TenantId,id:EntityId,operation:(repository:VehicleCommerceRepository)=>Promise<T>):Promise<T>{return this.tx(tenantId,async client=>{await client.query("SELECT id FROM vehicle_stock_items WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[tenantId,id]);return operation(new PostgresVehicleCommerceRepository(this.pool,client));});}
  async publish(value:Readonly<VehiclePublicationProps>,stockItem:Readonly<VehicleStockItemProps>){await this.tx(value.tenantId,async client=>{await client.query(`INSERT INTO vehicle_publications(id,tenant_id,organization_id,site_id,stock_item_id,channel,asking_price_cents,status,published_by,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[value.id,value.tenantId,value.organizationId,value.siteId,value.stockItemId,value.channel,value.askingPriceCents,value.status,value.publishedBy,value.publishedAt]);await client.query("UPDATE vehicle_stock_items SET status=$3,updated_at=$4 WHERE tenant_id=$1 AND id=$2",[stockItem.tenantId,stockItem.id,stockItem.status,stockItem.updatedAt]);await client.query(`INSERT INTO outbox_events(id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES(gen_random_uuid(),$1,$2,'commerce.vehicle_published.v1',$3,$4)`,[value.tenantId,value.id,JSON.stringify({organizationId:value.organizationId,siteId:value.siteId,stockItemId:value.stockItemId,channel:value.channel}),value.publishedAt]);});}
}
