import type { Pool, PoolClient } from "pg";
import { DomainError } from "../../packages/core/src/errors.ts";
import type { DomainEvent } from "../../packages/core/src/events.ts";
import type { EntityId, TenantId } from "../../packages/core/src/identity.ts";
import type { AvailabilitySlotProps, BookingProps, ServiceOfferingProps } from "../../packages/booking/src/booking.ts";
import type { BookingRepository } from "../../packages/booking/src/manage-bookings.ts";

export class PostgresBookingRepository implements BookingRepository {
  private readonly pool: Pool;
  constructor(pool: Pool) { this.pool = pool; }
  private async tx<T>(tenantId: TenantId, work: (client: PoolClient) => Promise<T>): Promise<T> { const client = await this.pool.connect(); try { await client.query("BEGIN"); await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenantId]); const result=await work(client); await client.query("COMMIT"); return result; } catch(error){ await client.query("ROLLBACK"); throw error; } finally{ client.release(); } }
  async saveOffering(v: Readonly<ServiceOfferingProps>): Promise<void> { await this.tx(v.tenantId,c=>c.query(`INSERT INTO service_offerings (id,tenant_id,organization_id,site_id,activity,name,duration_minutes,buffer_minutes,capacity,price_mode,price_cents,currency,published_channels,active,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[v.id,v.tenantId,v.organizationId,v.siteId,v.activity,v.name,v.durationMinutes,v.bufferMinutes,v.capacity,v.priceMode,v.priceCents??null,v.currency,v.publishedChannels,v.active,v.createdAt]).then(()=>undefined)); }
  async findOffering(tenantId: TenantId,id: EntityId): Promise<Readonly<ServiceOfferingProps>|null>{ return this.tx(tenantId,async c=>{const r=await c.query("SELECT * FROM service_offerings WHERE id=$1",[id]); const x=r.rows[0]; return x?{id:x.id,tenantId:x.tenant_id,organizationId:x.organization_id,siteId:x.site_id,activity:x.activity,name:x.name,durationMinutes:x.duration_minutes,bufferMinutes:x.buffer_minutes,capacity:x.capacity,priceMode:x.price_mode,priceCents:x.price_cents??undefined,currency:x.currency,publishedChannels:x.published_channels,active:x.active,createdAt:x.created_at.toISOString()} as ServiceOfferingProps:null;});}
  async saveSlot(v: Readonly<AvailabilitySlotProps>): Promise<void>{await this.tx(v.tenantId,c=>c.query(`INSERT INTO availability_slots (id,tenant_id,offering_id,site_id,starts_at,ends_at,capacity,booked_count,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[v.id,v.tenantId,v.offeringId,v.siteId,v.startsAt,v.endsAt,v.capacity,v.bookedCount,v.createdAt]).then(()=>undefined));}
  async findSlot(tenantId: TenantId,id: EntityId): Promise<Readonly<AvailabilitySlotProps>|null>{return this.tx(tenantId,async c=>{const r=await c.query("SELECT * FROM availability_slots WHERE id=$1",[id]);const x=r.rows[0];return x?{id:x.id,tenantId:x.tenant_id,offeringId:x.offering_id,siteId:x.site_id,startsAt:x.starts_at.toISOString(),endsAt:x.ends_at.toISOString(),capacity:x.capacity,bookedCount:x.booked_count,createdAt:x.created_at.toISOString()} as AvailabilitySlotProps:null;});}
  async findBooking(tenantId: TenantId,id: EntityId): Promise<Readonly<BookingProps>|null>{return this.tx(tenantId,async c=>{const r=await c.query("SELECT * FROM bookings WHERE id=$1",[id]);const x=r.rows[0];return x?this.mapBooking(x):null;});}
  async reserve(slot: Readonly<AvailabilitySlotProps>,booking: Readonly<BookingProps>,event: DomainEvent): Promise<void>{await this.tx(slot.tenantId,async c=>{const updated=await c.query("UPDATE availability_slots SET booked_count=booked_count+1 WHERE id=$1 AND booked_count<capacity",[slot.id]);if(updated.rowCount!==1)throw new DomainError("SLOT_FULL","This slot is no longer available");await c.query(`INSERT INTO bookings (id,tenant_id,organization_id,site_id,offering_id,slot_id,customer_id,asset_id,channel,acquisition_owner_organization_id,commission_basis_points,status,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[booking.id,booking.tenantId,booking.organizationId,booking.siteId,booking.offeringId,booking.slotId,booking.customerId,booking.assetId??null,booking.channel,booking.acquisitionOwnerOrganizationId??null,booking.commissionBasisPoints,booking.status,booking.createdAt]);await this.outbox(c,event);});}
  async cancel(slot: Readonly<AvailabilitySlotProps>,booking: Readonly<BookingProps>,event: DomainEvent): Promise<void>{await this.tx(slot.tenantId,async c=>{const updated=await c.query("UPDATE bookings SET status='cancelled',cancelled_at=$1 WHERE id=$2 AND status IN ('pending','confirmed')",[booking.cancelledAt,booking.id]);if(updated.rowCount!==1)throw new DomainError("BOOKING_NOT_CANCELLABLE","Booking cannot be cancelled");await c.query("UPDATE availability_slots SET booked_count=booked_count-1 WHERE id=$1 AND booked_count>0",[slot.id]);await this.outbox(c,event);});}
  private async outbox(c:PoolClient,e:DomainEvent):Promise<void>{await c.query("INSERT INTO outbox_events (id,tenant_id,aggregate_id,event_type,payload,occurred_at) VALUES ($1,$2,$3,$4,$5,$6)",[e.id,e.tenantId,e.aggregateId,e.type,e.payload,e.occurredAt]);}
  private mapBooking(x:Record<string,any>):BookingProps{return{id:x.id,tenantId:x.tenant_id,organizationId:x.organization_id,siteId:x.site_id,offeringId:x.offering_id,slotId:x.slot_id,customerId:x.customer_id,assetId:x.asset_id??undefined,channel:x.channel,acquisitionOwnerOrganizationId:x.acquisition_owner_organization_id??undefined,commissionBasisPoints:x.commission_basis_points,status:x.status,createdAt:x.created_at.toISOString(),cancelledAt:x.cancelled_at?.toISOString()} as BookingProps;}
}
