import{invariant}from"../../core/src/errors.ts";import{newEntityId,type EntityId,type TenantScoped}from"../../core/src/identity.ts";import type{AcquisitionChannel}from"../../customers/src/customer.ts";
export type RequestKind="service_quote"|"diagnostic"|"appointment"|"vehicle_purchase"|"vehicle_sale"|"rental"|"parts"|"body_shop"|"transport"|"other";export type OpportunityStatus="open"|"won"|"lost"|"cancelled";
export interface PipelineStage{key:string;label:string;order:number;terminal?:"won"|"lost"|undefined;requiredFields?:readonly string[]|undefined}
export interface PipelineProps extends TenantScoped{id:EntityId;organizationId:EntityId;activity:string;name:string;stages:readonly PipelineStage[];active:boolean;createdAt:string}
export class Pipeline{private readonly props:PipelineProps;private constructor(p:PipelineProps){this.props=p;}static create(input:Omit<PipelineProps,"id"|"active"|"createdAt">,now=new Date()){invariant(input.name.trim().length>=2,"PIPELINE_NAME_REQUIRED","Pipeline name is required");invariant(input.stages.length>=2,"PIPELINE_STAGES_REQUIRED","Pipeline needs at least two stages");const keys=input.stages.map(s=>s.key);invariant(new Set(keys).size===keys.length,"DUPLICATE_PIPELINE_STAGE","Pipeline stage keys must be unique");invariant(input.stages.filter(s=>s.terminal==="won").length===1,"PIPELINE_WON_STAGE_REQUIRED","Pipeline needs one won stage");invariant(input.stages.filter(s=>s.terminal==="lost").length===1,"PIPELINE_LOST_STAGE_REQUIRED","Pipeline needs one lost stage");return new Pipeline({...input,id:newEntityId(),name:input.name.trim(),stages:Object.freeze([...input.stages].sort((a,b)=>a.order-b.order)),active:true,createdAt:now.toISOString()});}snapshot(){return this.props;}}
export interface OpportunityProps extends TenantScoped{id:EntityId;organizationId:EntityId;siteId:EntityId;pipelineId:EntityId;stageKey:string;kind:RequestKind;title:string;customerId:EntityId;assetId?:EntityId|undefined;channel:AcquisitionChannel;acquisitionOwnerOrganizationId?:EntityId|undefined;assignedTo?:EntityId|undefined;estimatedValueCents?:number|undefined;currency:string;status:OpportunityStatus;lostReason?:string|undefined;metadata:Readonly<Record<string,string|number|boolean>>;createdAt:string;updatedAt:string}
export class Opportunity{private props:OpportunityProps;private constructor(p:OpportunityProps){this.props=p;}static create(input:Omit<OpportunityProps,"id"|"status"|"lostReason"|"createdAt"|"updatedAt">,pipeline:Readonly<PipelineProps>,now=new Date()){invariant(input.tenantId===pipeline.tenantId,"TENANT_MISMATCH","Opportunity and pipeline tenant mismatch");invariant(input.organizationId===pipeline.organizationId,"ORGANIZATION_MISMATCH","Opportunity and pipeline organization mismatch");invariant(input.channel==="central_marketplace"||Boolean(input.acquisitionOwnerOrganizationId),"OPPORTUNITY_ATTRIBUTION_REQUIRED","Direct opportunity needs an owning organization");invariant(input.title.trim().length>=2,"OPPORTUNITY_TITLE_REQUIRED","Opportunity title is required");const first=pipeline.stages[0]!;const at=now.toISOString();return new Opportunity({...input,id:newEntityId(),title:input.title.trim(),stageKey:first.key,status:"open",metadata:Object.freeze({...input.metadata}),createdAt:at,updatedAt:at});}static restore(p:OpportunityProps){return new Opportunity(p);}move(stageKey:string,pipeline:Readonly<PipelineProps>,providedFields:readonly string[],now=new Date()){invariant(this.props.status==="open","OPPORTUNITY_CLOSED","Closed opportunity cannot move");const current=pipeline.stages.find(s=>s.key===this.props.stageKey),next=pipeline.stages.find(s=>s.key===stageKey);invariant(current&&next,"PIPELINE_STAGE_NOT_FOUND","Pipeline stage was not found");invariant(next.order>=current.order||Boolean(next.terminal),"BACKWARD_TRANSITION_DENIED","Backward transition requires a dedicated reopen action");invariant((next.requiredFields??[]).every(f=>providedFields.includes(f)),"STAGE_REQUIREMENTS_MISSING","Required stage data is missing");this.props={...this.props,stageKey:next.key,status:next.terminal??"open",updatedAt:now.toISOString()};}lose(reason:string,pipeline:Readonly<PipelineProps>,now=new Date()){invariant(reason.trim().length>=2,"LOST_REASON_REQUIRED","Lost reason is required");const lost=pipeline.stages.find(s=>s.terminal==="lost");invariant(lost,"LOST_STAGE_NOT_FOUND","Lost stage is missing");this.props={...this.props,stageKey:lost.key,status:"lost",lostReason:reason.trim(),updatedAt:now.toISOString()};}snapshot(){return this.props;}}
export interface CrmTaskProps extends TenantScoped{id:EntityId;opportunityId:EntityId;assignedTo?:EntityId|undefined;type:"call"|"email"|"sms"|"appointment"|"document"|"custom";title:string;dueAt:string;status:"open"|"completed"|"cancelled";automationKey?:string|undefined;createdAt:string}
export class CrmTask{static create(input:Omit<CrmTaskProps,"id"|"status"|"createdAt">,now=new Date()):CrmTaskProps{invariant(input.title.trim().length>=2,"TASK_TITLE_REQUIRED","Task title is required");return{...input,id:newEntityId(),title:input.title.trim(),status:"open",createdAt:now.toISOString()};}}
export interface AutomationRule{key:string;trigger:"opportunity_created"|"stage_entered";stageKey?:string|undefined;delayMinutes:number;taskType:CrmTaskProps["type"];taskTitle:string;active:boolean}
