import test from "node:test";
import assert from "node:assert/strict";
import { AuditRecorder,InMemoryAuditSink } from "../audit/src/audit.ts";
import { Membership } from "../organizations/src/access-control.ts";
import { tenantId,type EntityId } from "../core/src/identity.ts";
import { ManageVehicleCommerce } from "../vehicle-commerce/src/vehicle-commerce.ts";
import { InMemoryVehicleCommerceRepository } from "../vehicle-commerce/src/in-memory-vehicle-commerce-repository.ts";
import { PlatformApplication } from "../../apps/api/src/application.ts";
import { buildApp } from "../../apps/api/src/build-app.ts";
import { MapTokenVerifier,RequestContextResolver } from "../../apps/api/src/context-resolver.ts";
import { InMemoryPlatformRepository } from "../../apps/api/src/in-memory-platform-repository.ts";
import { InMemoryMembershipReader,RouteAuthorizer } from "../../apps/api/src/route-authorizer.ts";

test("publishes merchandised vehicle stock through scoped HTTP routes",async()=>{const tenant="11111111-1111-4111-8111-111111111111",actor="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",organizationId="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb" as EntityId,siteId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" as EntityId,assetId="dddddddd-dddd-4ddd-8ddd-dddddddddddd" as EntityId;const contexts=new RequestContextResolver(new MapTokenVerifier(new Map([["commerce-token",{tenantId:tenant,actorId:actor}]])));const membership=Membership.create({tenantId:tenantId(tenant),organizationId,userId:actor as EntityId,role:"owner",siteIds:[],extraPermissions:[]}).snapshot();const repository=new InMemoryVehicleCommerceRepository();repository.assets.add(`${tenant}:${assetId}`);repository.sites.set(`${tenant}:${siteId}`,organizationId);const commerce=new ManageVehicleCommerce(repository,()=>new Date("2026-07-22T10:00:00Z"));const app=buildApp({application:new PlatformApplication(new InMemoryPlatformRepository(),new AuditRecorder(new InMemoryAuditSink())),contexts,authorizer:new RouteAuthorizer(new InMemoryMembershipReader([membership])),modules:{vehicleCommerce:commerce}});const headers={authorization:"Bearer commerce-token"};const acquired=await app.inject({method:"POST",url:"/v1/vehicle-stock",headers,payload:{organizationId,siteId,assetId,acquisitionMode:"trade_in",acquisitionCostCents:1200000}});assert.equal(acquired.statusCode,200);const id=acquired.json().id;await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/start-preparation`,headers});const check=await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/preparation-checks`,headers,payload:{label:"Contrôle sécurité",required:true}});await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/preparation-checks/${check.json().id}/complete`,headers});await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/media`,headers,payload:{kind:"image",storageKey:`vehicles/${id}/cover.jpg`,position:0,primary:true}});assert.equal((await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/ready`,headers,payload:{askingPriceCents:1590000}})).statusCode,200);const publication=await app.inject({method:"POST",url:`/v1/vehicle-stock/${id}/publications`,headers,payload:{channel:"central_marketplace"}});assert.equal(publication.statusCode,200);assert.equal(publication.json().publication.channel,"central_marketplace");await app.close();});
