import test from "node:test";
import assert from "node:assert/strict";
import { DomainError } from "../../core/src/errors.ts";
import { newEntityId, tenantId, type RequestContext } from "../../core/src/identity.ts";
import { InMemoryInventoryRepository } from "../src/in-memory-inventory-repository.ts";
import { ManageInventory } from "../src/manage-inventory.ts";

const context: RequestContext = { tenantId: tenantId("11111111-1111-4111-8111-111111111111"), actorId: newEntityId(), correlationId: "inventory" };
async function fixture() { const repository = new InMemoryInventoryRepository(); const service = new ManageInventory(repository, () => new Date("2026-07-20T18:00:00Z")); const organizationId = newEntityId(); const siteId = newEntityId(); const part = await service.createPart(context, { organizationId, sku: "fil-001", name: "Filtre à huile", unitCostCents: 800, salePriceCents: 1800, reorderPoint: 2, reorderQuantity: 10 }); const supplier = await service.createSupplier(context, { organizationId, code: "four-001", name: "Fournitures Auto", email: "achats@example.com" }); await service.receive(context, siteId, part.id, 5); return { repository, service, organizationId, siteId, part, supplier }; }

test("tracks on-hand, reserved and available stock", async () => { const { repository, service, siteId, part } = await fixture(); await service.reserve(context, { siteId, partId: part.id, workOrderId: newEntityId(), quantity: 2 }); assert.equal(repository.positions[0]!.onHand, 5); assert.equal(repository.positions[0]!.reserved, 2); });
test("prevents over-reservation", async () => { const { service, siteId, part } = await fixture(); await assert.rejects(() => service.reserve(context, { siteId, partId: part.id, workOrderId: newEntityId(), quantity: 6 }), (error: unknown) => error instanceof DomainError && error.code === "INSUFFICIENT_STOCK"); });
test("consumes or releases reservations without corrupting stock", async () => { const { repository, service, siteId, part } = await fixture(); const first = await service.reserve(context, { siteId, partId: part.id, workOrderId: newEntityId(), quantity: 2 }); await service.consume(context, first.id); assert.equal(repository.positions[0]!.onHand, 3); const second = await service.reserve(context, { siteId, partId: part.id, workOrderId: newEntityId(), quantity: 1 }); await service.release(context, second.id); assert.equal(repository.positions[0]!.reserved, 0); });
test("creates a supplier-scoped numbered purchase order", async () => { const { service, organizationId, siteId, part, supplier } = await fixture(); const value = await service.createPurchaseOrder(context, { organizationId, siteId, supplierId: supplier.id, lines: [{ partId: part.id, quantity: 10, unitCostCents: 750 }] }); assert.equal(value.number, "CF-2026-00001"); });
test("receives an order partially then fully and calculates weighted average valuation", async () => { const { repository, service, organizationId, siteId, part, supplier } = await fixture(); const draft = await service.createPurchaseOrder(context, { organizationId, siteId, supplierId: supplier.id, lines: [{ partId: part.id, quantity: 10, unitCostCents: 1000 }] }); await service.order(context, draft.id); const partial = await service.receivePurchaseOrder(context, draft.id, [{ partId: part.id, quantity: 4, unitCostCents: 1000 }]); assert.equal(partial.order.status, "partially_received"); assert.equal(partial.positions[0]!.averageUnitCostCents, 444); const complete = await service.receivePurchaseOrder(context, draft.id, [{ partId: part.id, quantity: 6, unitCostCents: 1000 }]); assert.equal(complete.order.status, "received"); assert.equal(repository.receipts.length, 2); assert.equal(repository.positions[0]!.onHand, 15); });
test("rejects over-receipt and cross-organization supplier", async () => { const { service, organizationId, siteId, part, supplier } = await fixture(); const draft = await service.createPurchaseOrder(context, { organizationId, siteId, supplierId: supplier.id, lines: [{ partId: part.id, quantity: 2, unitCostCents: 900 }] }); await service.order(context, draft.id); await assert.rejects(() => service.receivePurchaseOrder(context, draft.id, [{ partId: part.id, quantity: 3, unitCostCents: 900 }]), (error: unknown) => error instanceof DomainError && error.code === "RECEIPT_EXCEEDS_ORDER"); await assert.rejects(() => service.createPurchaseOrder(context, { organizationId: newEntityId(), siteId, supplierId: supplier.id, lines: [{ partId: part.id, quantity: 1, unitCostCents: 900 }] }), (error: unknown) => error instanceof DomainError && error.code === "SUPPLIER_SCOPE_MISMATCH"); });
test("isolates inventory reads by tenant", async () => { const { service, organizationId, siteId, part, supplier } = await fixture(); const order = await service.createPurchaseOrder(context, { organizationId, siteId, supplierId: supplier.id, lines: [{ partId: part.id, quantity: 1, unitCostCents: 900 }] }); const other = { ...context, tenantId: tenantId("22222222-2222-4222-8222-222222222222") }; await assert.rejects(() => service.order(other, order.id), (error: unknown) => error instanceof DomainError && error.code === "PURCHASE_ORDER_NOT_FOUND"); });
