import{invariant}from"../../core/src/errors.ts";import{newEntityId,type EntityId,type TenantScoped}from"../../core/src/identity.ts";
export type WorkflowPriority="low"|"normal"|"high"|"urgent";export type WorkflowStatus="open"|"completed"|"cancelled";
export interface WorkflowStep{key:string;label:string;order:number;terminal?:boolean|undefined;requiredFields?:readonly string[]|undefined;defaultRole?:string|undefined;slaMinutes?:number|undefined}
export interface WorkflowDefinitionProps extends TenantScoped{id:EntityId;organizationId:EntityId;activity:string;key:string;name:string;steps:readonly WorkflowStep[];active:boolean;version:number;createdAt:string}
export class WorkflowDefinition{static create(input:Omit<WorkflowDefinitionProps,"id"|"active"|"version"|"createdAt">,now=new Date()):WorkflowDefinitionProps{invariant(/^[a-z0-9_.-]{2,80}$/.test(input.key),"INVALID_WORKFLOW_KEY","Workflow key is invalid");invariant(input.steps.length>=2,"WORKFLOW_STEPS_REQUIRED","Workflow needs at least two steps");invariant(new Set(input.steps.map(x=>x.key)).size===input.steps.length,"DUPLICATE_WORKFLOW_STEP","Workflow step keys must be unique");invariant(input.steps.some(x=>x.terminal),"TERMINAL_STEP_REQUIRED","Workflow needs a terminal step");for(const step of input.steps)invariant(step.slaMinutes===undefined||step.slaMinutes>0,"INVALID_STEP_SLA","Step SLA must be positive");return{...input,id:newEntityId(),name:input.name.trim(),steps:Object.freeze([...input.steps].sort((a,b)=>a.order-b.order)),active:true,version:1,createdAt:now.toISOString()};}}
export interface WorkflowInstanceProps extends TenantScoped{id:EntityId;organizationId:EntityId;siteId:EntityId;definitionId:EntityId;subjectType:string;subjectId:EntityId;stepKey:string;status:WorkflowStatus;priority:WorkflowPriority;data:Readonly<Record<string,string|number|boolean>>;version:number;startedAt:string;updatedAt:string;completedAt?:string|undefined}
export class WorkflowInstance{private props:WorkflowInstanceProps;private constructor(p:WorkflowInstanceProps){this.props=p;}static start(input:Omit<WorkflowInstanceProps,"id"|"stepKey"|"status"|"version"|"startedAt"|"updatedAt"|"completedAt">,definition:WorkflowDefinitionProps,now=new Date()){invariant(input.tenantId===definition.tenantId,"TENANT_MISMATCH","Workflow tenant mismatch");const at=now.toISOString();return new WorkflowInstance({...input,id:newEntityId(),stepKey:definition.steps[0]!.key,status:"open",version:1,startedAt:at,updatedAt:at});}static restore(p:WorkflowInstanceProps){return new WorkflowInstance(p);}transition(to:string,definition:WorkflowDefinitionProps,expectedVersion:number,fields:Readonly<Record<string,string|number|boolean>>,now=new Date()){invariant(this.props.status==="open","WORKFLOW_CLOSED","Workflow is closed");invariant(this.props.version===expectedVersion,"WORKFLOW_VERSION_CONFLICT","Workflow was modified by another user");const current=definition.steps.find(x=>x.key===this.props.stepKey),next=definition.steps.find(x=>x.key===to);invariant(current&&next,"WORKFLOW_STEP_NOT_FOUND","Workflow step was not found");invariant(next.order===current.order+1||Boolean(next.terminal),"WORKFLOW_TRANSITION_DENIED","Workflow transition is not allowed");const data={...this.props.data,...fields};invariant((next.requiredFields??[]).every(key=>Object.hasOwn(data,key)),"WORKFLOW_FIELDS_MISSING","Required workflow data is missing");const at=now.toISOString();this.props={...this.props,stepKey:next.key,status:next.terminal?"completed":"open",data:Object.freeze(data),version:this.props.version+1,updatedAt:at,completedAt:next.terminal?at:undefined};}snapshot(){return this.props;}}
export interface WorkItemProps extends TenantScoped{id:EntityId;instanceId:EntityId;stepKey:string;title:string;assignedTo?:EntityId|undefined;assignedRole?:string|undefined;priority:WorkflowPriority;dueAt?:string|undefined;status:"open"|"completed"|"cancelled";createdAt:string;completedAt?:string|undefined}
export class WorkItem{static create(input:Omit<WorkItemProps,"id"|"status"|"createdAt"|"completedAt">,now=new Date()):WorkItemProps{return{...input,id:newEntityId(),status:"open",createdAt:now.toISOString()};}static complete(v:WorkItemProps,now=new Date()):WorkItemProps{invariant(v.status==="open","WORK_ITEM_CLOSED","Work item is closed");return{...v,status:"completed",completedAt:now.toISOString()};}static assign(v:WorkItemProps,assignedTo:EntityId):WorkItemProps{invariant(v.status==="open","WORK_ITEM_CLOSED","Work item is closed");return{...v,assignedTo};}}
