import { createHash,randomBytes,timingSafeEqual } from "node:crypto";
import { invariant } from "../../core/src/errors.ts";
import { newEntityId,type EntityId,type TenantScoped } from "../../core/src/identity.ts";

export type DocumentKind="invoice"|"quote"|"work_order"|"inspection_report"|"registration"|"insurance"|"warranty"|"photo"|"identity"|"cession_certificate"|"delivery_receipt"|"other";
export type DocumentClassification="private"|"customer_shared"|"professional_shared"|"resale_public";
export interface DocumentProps extends TenantScoped{id:EntityId;ownerCustomerId:EntityId;assetId?:EntityId|undefined;passportId?:EntityId|undefined;kind:DocumentKind;name:string;mimeType:string;sizeBytes:number;contentHash:string;storageKey:string;classification:DocumentClassification;retentionUntil?:string|undefined;version:number;createdBy:EntityId;createdAt:string}
export class DocumentRecord{private readonly props:DocumentProps;private constructor(p:DocumentProps){this.props=p;}static create(input:Omit<DocumentProps,"id"|"version"|"createdAt">,now=new Date()):DocumentRecord{invariant(input.name.trim().length>=2,"DOCUMENT_NAME_REQUIRED","Document name is required");invariant(input.sizeBytes>0&&input.sizeBytes<=100*1024*1024,"INVALID_DOCUMENT_SIZE","Document size is invalid");invariant(/^[a-f0-9]{64}$/i.test(input.contentHash),"INVALID_DOCUMENT_HASH","SHA-256 content hash is required");invariant(/^[a-z0-9][a-z0-9+.-]+\/[a-z0-9][a-z0-9+.-]+$/i.test(input.mimeType),"INVALID_MIME_TYPE","MIME type is invalid");invariant(Boolean(input.assetId||input.passportId||input.kind==="identity"),"DOCUMENT_CONTEXT_REQUIRED","Document needs an asset, passport or identity context");return new DocumentRecord({...input,id:newEntityId(),name:input.name.trim(),contentHash:input.contentHash.toLowerCase(),version:1,createdAt:now.toISOString()});}snapshot():Readonly<DocumentProps>{return this.props;}}

export type ConsentPurpose="service_delivery"|"diagnosis"|"insurance_claim"|"vehicle_sale"|"fleet_management"|"legal_obligation";
export type ConsentScope="passport_summary"|"maintenance_history"|"documents"|"contact_details"|"vehicle_data";
export interface ConsentProps extends TenantScoped{id:EntityId;customerId:EntityId;granteeOrganizationId:EntityId;purpose:ConsentPurpose;scopes:readonly ConsentScope[];assetIds:readonly EntityId[];grantedAt:string;expiresAt:string;revokedAt?:string|undefined;proof:string;createdAt:string}
export class Consent{private props:ConsentProps;private constructor(p:ConsentProps){this.props=p;}static grant(input:Omit<ConsentProps,"id"|"grantedAt"|"revokedAt"|"proof"|"createdAt">,now=new Date()):Consent{invariant(input.scopes.length>0,"CONSENT_SCOPE_REQUIRED","Consent needs at least one scope");invariant(input.assetIds.length>0,"CONSENT_ASSET_REQUIRED","Consent needs at least one asset");invariant(new Date(input.expiresAt)>now,"CONSENT_MUST_EXPIRE","Consent expiry must be in the future");const grantedAt=now.toISOString();const proof=createHash("sha256").update([input.tenantId,input.customerId,input.granteeOrganizationId,input.purpose,[...input.scopes].sort().join(","),[...input.assetIds].sort().join(","),grantedAt,input.expiresAt].join("|")).digest("hex");return new Consent({...input,id:newEntityId(),scopes:Object.freeze([...new Set(input.scopes)]),assetIds:Object.freeze([...new Set(input.assetIds)]),grantedAt,proof,createdAt:grantedAt});}static restore(p:ConsentProps):Consent{return new Consent(p);}revoke(now=new Date()){invariant(!this.props.revokedAt,"CONSENT_ALREADY_REVOKED","Consent is already revoked");this.props={...this.props,revokedAt:now.toISOString()};}allows(input:{organizationId:EntityId;assetId:EntityId;scope:ConsentScope;now?:Date}):boolean{const now=input.now??new Date();return !this.props.revokedAt&&now<new Date(this.props.expiresAt)&&this.props.granteeOrganizationId===input.organizationId&&this.props.assetIds.includes(input.assetId)&&this.props.scopes.includes(input.scope);}snapshot():Readonly<ConsentProps>{return this.props;}}

export interface ShareGrantProps extends TenantScoped{id:EntityId;documentId:EntityId;issuedToCustomerId?:EntityId|undefined;issuedToOrganizationId?:EntityId|undefined;tokenHash:string;expiresAt:string;maxDownloads:number;downloadCount:number;revokedAt?:string|undefined;createdBy:EntityId;createdAt:string}
export class ShareGrant{private props:ShareGrantProps;private constructor(p:ShareGrantProps){this.props=p;}static issue(input:Omit<ShareGrantProps,"id"|"tokenHash"|"expiresAt"|"downloadCount"|"revokedAt"|"createdAt">&{ttlMinutes:number},now=new Date()):{grant:ShareGrant;token:string}{invariant(Boolean(input.issuedToCustomerId||input.issuedToOrganizationId),"SHARE_RECIPIENT_REQUIRED","A share recipient is required");invariant(input.ttlMinutes>=5&&input.ttlMinutes<=43200,"INVALID_SHARE_TTL","Share validity is invalid");invariant(input.maxDownloads>=1&&input.maxDownloads<=100,"INVALID_DOWNLOAD_LIMIT","Download limit is invalid");const token=randomBytes(32).toString("base64url"),tokenHash=ShareGrant.hash(token);const {ttlMinutes,...base}=input;return{token,grant:new ShareGrant({...base,id:newEntityId(),tokenHash,expiresAt:new Date(now.getTime()+ttlMinutes*60000).toISOString(),downloadCount:0,createdAt:now.toISOString()})};}static hash(t:string){return createHash("sha256").update(t).digest("hex");}static restore(p:ShareGrantProps){return new ShareGrant(p);}consume(token:string,now=new Date()){invariant(!this.props.revokedAt,"SHARE_REVOKED","Share was revoked");invariant(now<new Date(this.props.expiresAt),"SHARE_EXPIRED","Share has expired");invariant(this.props.downloadCount<this.props.maxDownloads,"DOWNLOAD_LIMIT_REACHED","Download limit reached");const a=Buffer.from(this.props.tokenHash,"hex"),b=Buffer.from(ShareGrant.hash(token),"hex");invariant(a.length===b.length&&timingSafeEqual(a,b),"INVALID_SHARE_TOKEN","Share token is invalid");this.props={...this.props,downloadCount:this.props.downloadCount+1};}snapshot():Readonly<ShareGrantProps>{return this.props;}}

export interface DisclosureLogProps extends TenantScoped{id:EntityId;documentId:EntityId;actorId:EntityId;recipientType:"customer"|"organization";recipientId:EntityId;action:"view"|"download";legalBasis:"consent"|"contract"|"legal_obligation";consentId?:EntityId|undefined;occurredAt:string;ipHash?:string|undefined}
