import type { FastifyInstance } from "fastify";
import { z } from "zod";
import type { EntityId } from "../../../../packages/core/src/identity.ts";
import type { ManageVehicleCommerce } from "../../../../packages/vehicle-commerce/src/vehicle-commerce.ts";
import type { RequestContextResolver } from "../context-resolver.ts";
import type { RouteAuthorizer } from "../route-authorizer.ts";

const uuid=z.string().uuid();
const acquisition=z.object({organizationId:uuid,siteId:uuid,assetId:uuid,acquisitionMode:z.enum(["purchase","trade_in","consignment"]),acquisitionCostCents:z.number().int().min(0)});
const idParams=z.object({id:uuid});
const readyBody=z.object({askingPriceCents:z.number().int().positive()});
const publishBody=z.object({channel:z.enum(["professional_website","professional_app","central_marketplace"])});
const checkBody=z.object({label:z.string().trim().min(2),required:z.boolean()});
const checkParams=z.object({id:uuid,checkId:uuid});
const mediaBody=z.object({kind:z.enum(["image","video"]),storageKey:z.string().trim().min(3),position:z.number().int().min(0),primary:z.boolean()});
const saleBody=z.object({buyerCustomerId:uuid,salePriceCents:z.number().int().positive()});
const deliveryBody=z.object({plannedAt:z.string().datetime({offset:true})});
const completeDeliveryBody=z.object({handoverOdometerKm:z.number().int().min(0),notes:z.string().trim().max(2000).optional()});
const transferBody=z.object({documentIds:z.array(uuid).min(1)});
const cessionDossierBody=z.object({certificateDocumentId:uuid,deliveryReceiptDocumentId:uuid});
const flashSaleBody=z.object({priceCents:z.number().int().positive(),startsAt:z.string().datetime({offset:true}),endsAt:z.string().datetime({offset:true}),channels:z.array(z.enum(["professional_website","professional_app","central_marketplace"])).min(1)});
const auctionBody=z.object({channel:z.enum(["professional_website","professional_app","central_marketplace"]),startingPriceCents:z.number().int().positive(),reservePriceCents:z.number().int().positive(),minimumIncrementCents:z.number().int().positive(),startsAt:z.string().datetime({offset:true}),endsAt:z.string().datetime({offset:true})});
const auctionParams=z.object({id:uuid,auctionId:uuid});
const bidBody=z.object({bidderCustomerId:uuid,amountCents:z.number().int().positive()});

export function registerVehicleCommerceRoutes(app:FastifyInstance,contexts:RequestContextResolver,authorizer:RouteAuthorizer,commerce:ManageVehicleCommerce):void{
  app.post("/v1/vehicle-stock",async request=>{const context=await contexts.resolve(request);const body=acquisition.parse(request.body);await authorizer.require(context,"commerce.manage",{organizationId:body.organizationId as EntityId,siteId:body.siteId as EntityId});return commerce.acquire(context,{...body,organizationId:body.organizationId as EntityId,siteId:body.siteId as EntityId,assetId:body.assetId as EntityId});});
  app.post("/v1/vehicle-stock/:id/start-preparation",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.startPreparation(context,params.id as EntityId);});
  app.post("/v1/vehicle-stock/:id/preparation-checks",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=checkBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.addPreparationCheck(context,params.id as EntityId,body);});
  app.post("/v1/vehicle-stock/:id/preparation-checks/:checkId/complete",async request=>{const context=await contexts.resolve(request);const params=checkParams.parse(request.params);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.completePreparationCheck(context,params.id as EntityId,params.checkId as EntityId);});
  app.post("/v1/vehicle-stock/:id/media",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=mediaBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.addMedia(context,params.id as EntityId,body);});
  app.post("/v1/vehicle-stock/:id/ready",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=readyBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.markReady(context,params.id as EntityId,body.askingPriceCents);});
  app.post("/v1/vehicle-stock/:id/publications",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=publishBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.publish(context,params.id as EntityId,body.channel);});
  app.post("/v1/vehicle-stock/:id/sale",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=saleBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.sell(context,params.id as EntityId,{buyerCustomerId:body.buyerCustomerId as EntityId,salePriceCents:body.salePriceCents});});
  app.post("/v1/vehicle-stock/:id/delivery",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=deliveryBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.scheduleDelivery(context,params.id as EntityId,body.plannedAt);});
  app.post("/v1/vehicle-stock/:id/delivery/complete",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=completeDeliveryBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.completeDelivery(context,params.id as EntityId,body);});
  app.post("/v1/vehicle-stock/:id/ownership-transfer",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=transferBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.transferOwnership(context,params.id as EntityId,body.documentIds as EntityId[]);});
  app.post("/v1/vehicle-stock/:id/cession-dossier",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=cessionDossierBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.issueCessionDossier(context,params.id as EntityId,{certificateDocumentId:body.certificateDocumentId as EntityId,deliveryReceiptDocumentId:body.deliveryReceiptDocumentId as EntityId});});
  app.post("/v1/vehicle-stock/:id/flash-sales",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=flashSaleBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.scheduleFlashSale(context,params.id as EntityId,body);});
  app.post("/v1/vehicle-stock/:id/flash-sales/cancel",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.cancelFlashSale(context,params.id as EntityId);});
  app.post("/v1/vehicle-stock/:id/withdraw",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.withdraw(context,params.id as EntityId);});
  app.post("/v1/vehicle-stock/:id/auctions",async request=>{const context=await contexts.resolve(request);const params=idParams.parse(request.params),body=auctionBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.scheduleAuction(context,params.id as EntityId,body);});
  app.post("/v1/vehicle-stock/:id/auctions/:auctionId/bids",async request=>{const context=await contexts.resolve(request);const params=auctionParams.parse(request.params),body=bidBody.parse(request.body);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.placeAuctionBid(context,params.id as EntityId,params.auctionId as EntityId,{bidderCustomerId:body.bidderCustomerId as EntityId,amountCents:body.amountCents});});
  app.post("/v1/vehicle-stock/:id/auctions/:auctionId/close",async request=>{const context=await contexts.resolve(request);const params=auctionParams.parse(request.params);await authorizer.require(context,"commerce.manage",await commerce.scope(context,params.id as EntityId));return commerce.closeAuction(context,params.id as EntityId,params.auctionId as EntityId);});
}
