import test from "node:test";
import assert from "node:assert/strict";
import { DomainError } from "../../core/src/errors.ts";
import { newEntityId,tenantId,type RequestContext } from "../../core/src/identity.ts";
import { InMemoryVehicleCommerceRepository } from "../src/in-memory-vehicle-commerce-repository.ts";
import { ManageVehicleCommerce } from "../src/vehicle-commerce.ts";

const context:RequestContext={tenantId:tenantId("11111111-1111-4111-8111-111111111111"),actorId:newEntityId(),correlationId:"vehicle-commerce"};
function fixture(){const repository=new InMemoryVehicleCommerceRepository(),organizationId=newEntityId(),siteId=newEntityId(),assetId=newEntityId();repository.assets.add(`${context.tenantId}:${assetId}`);repository.sites.set(`${context.tenantId}:${siteId}`,organizationId);return{repository,service:new ManageVehicleCommerce(repository,()=>new Date("2026-07-22T10:00:00Z")),organizationId,siteId,assetId};}
test("moves acquired vehicle through preparation to multichannel publication",async()=>{const{repository,service,organizationId,siteId,assetId}=fixture();const item=await service.acquire(context,{organizationId,siteId,assetId,acquisitionMode:"trade_in",acquisitionCostCents:1200000});await service.startPreparation(context,item.id);await service.markReady(context,item.id,1590000);await service.publish(context,item.id,"professional_website");await service.publish(context,item.id,"central_marketplace");assert.equal(repository.publications.length,2);assert.equal(repository.items[0]!.status,"published");});
test("rejects publication before preparation and duplicate channel publication",async()=>{const{service,organizationId,siteId,assetId}=fixture();const item=await service.acquire(context,{organizationId,siteId,assetId,acquisitionMode:"purchase",acquisitionCostCents:100});await assert.rejects(()=>service.publish(context,item.id,"professional_app"),(error:unknown)=>error instanceof DomainError&&error.code==="STOCK_ITEM_NOT_PUBLISHABLE");await service.startPreparation(context,item.id);await service.markReady(context,item.id,200);await service.publish(context,item.id,"professional_app");await assert.rejects(()=>service.publish(context,item.id,"professional_app"),(error:unknown)=>error instanceof DomainError&&error.code==="CHANNEL_ALREADY_PUBLISHED");});
test("serializes concurrent publication attempts",async()=>{const{repository,service,organizationId,siteId,assetId}=fixture();const item=await service.acquire(context,{organizationId,siteId,assetId,acquisitionMode:"consignment",acquisitionCostCents:0});await service.startPreparation(context,item.id);await service.markReady(context,item.id,500);const results=await Promise.allSettled([service.publish(context,item.id,"central_marketplace"),service.publish(context,item.id,"central_marketplace")]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);assert.equal(repository.publications.length,1);});
test("enforces tenant, asset and site scope",async()=>{const{service,organizationId,siteId,assetId}=fixture();await assert.rejects(()=>service.acquire(context,{organizationId,siteId:newEntityId(),assetId,acquisitionMode:"purchase",acquisitionCostCents:0}),(error:unknown)=>error instanceof DomainError&&error.code==="SITE_SCOPE_MISMATCH");const other={...context,tenantId:tenantId("22222222-2222-4222-8222-222222222222")};const item=await service.acquire(context,{organizationId,siteId,assetId,acquisitionMode:"purchase",acquisitionCostCents:0});await assert.rejects(()=>service.startPreparation(other,item.id),(error:unknown)=>error instanceof DomainError&&error.code==="STOCK_ITEM_NOT_FOUND");});
