import { invariant } from "../../core/src/errors.ts";
import { newEntityId,type EntityId,type RequestContext,type TenantId } from "../../core/src/identity.ts";
import { Deadline,Passport,PassportEntry,QrGrant,type DeadlineProps,type PassportEntryProps,type PassportProps,type QrGrantProps,type QrPurpose } from "./passport.ts";

export interface PassportRepository { savePassport(v:Readonly<PassportProps>):Promise<void>; findPassportByAsset(tenantId:TenantId,assetId:EntityId):Promise<Readonly<PassportProps>|null>; saveEntry(v:Readonly<PassportEntryProps>):Promise<void>; saveDeadline(v:Readonly<DeadlineProps>):Promise<void>; saveGrant(v:Readonly<QrGrantProps>):Promise<void>; findGrantByHash(tenantId:TenantId,hash:string):Promise<Readonly<QrGrantProps>|null>; updateGrant(v:Readonly<QrGrantProps>):Promise<void>; listDueDeadlines(tenantId:TenantId,before:string):Promise<readonly Readonly<DeadlineProps>[]>; hasReminder(tenantId:TenantId,deadlineId:EntityId,windowDays:number):Promise<boolean>; saveReminder(v:ReminderProps):Promise<void> }
export interface ReminderProps extends TenantIdCarrier { id:EntityId;deadlineId:EntityId;customerId:EntityId;channel:"email"|"sms"|"push";windowDays:number;scheduledFor:string;status:"pending"|"sent"|"cancelled";createdAt:string }
interface TenantIdCarrier{tenantId:TenantId}

export class ManagePassports{
  private readonly repository:PassportRepository;private readonly now:()=>Date;
  constructor(repository:PassportRepository,now=()=>new Date()){this.repository=repository;this.now=now;}
  async create(context:RequestContext,input:{assetId:EntityId;ownerCustomerId:EntityId}):Promise<Readonly<PassportProps>>{invariant(!(await this.repository.findPassportByAsset(context.tenantId,input.assetId)),"PASSPORT_ALREADY_EXISTS","Asset already has a passport");const value=Passport.create({tenantId:context.tenantId,...input},this.now()).snapshot();await this.repository.savePassport(value);return value;}
  async addEntry(context:RequestContext,input:Omit<PassportEntryProps,"id"|"tenantId"|"createdBy"|"createdAt"|"evidenceHash">):Promise<Readonly<PassportEntryProps>>{const value=PassportEntry.create({tenantId:context.tenantId,createdBy:context.actorId,...input},this.now()).snapshot();await this.repository.saveEntry(value);return value;}
  async addDeadline(context:RequestContext,input:Omit<DeadlineProps,"id"|"tenantId"|"status"|"createdAt">):Promise<Readonly<DeadlineProps>>{const value=Deadline.create({tenantId:context.tenantId,...input},this.now()).snapshot();await this.repository.saveDeadline(value);return value;}
  async issueQr(context:RequestContext,input:{passportId:EntityId;purpose:QrPurpose;ttlMinutes:number;maxUses:number}):Promise<{grant:Readonly<QrGrantProps>;token:string}>{const issued=QrGrant.issue({tenantId:context.tenantId,passportId:input.passportId,purpose:input.purpose,maxUses:input.maxUses,createdBy:context.actorId,ttlMinutes:input.ttlMinutes},this.now());await this.repository.saveGrant(issued.grant.snapshot());return{grant:issued.grant.snapshot(),token:issued.token};}
  async consumeQr(context:RequestContext,token:string):Promise<Readonly<QrGrantProps>>{const stored=await this.repository.findGrantByHash(context.tenantId,QrGrant.hash(token));invariant(stored,"QR_NOT_FOUND","QR access was not found");const grant=QrGrant.restore({...stored});grant.consume(token,this.now());await this.repository.updateGrant(grant.snapshot());return grant.snapshot();}
  async scheduleReminders(context:RequestContext,customerId:EntityId,windowDays:number,channel:ReminderProps["channel"]):Promise<ReminderProps[]>{invariant([1,7,14,30,60,90].includes(windowDays),"INVALID_REMINDER_WINDOW","Reminder window is not supported");const before=new Date(this.now().getTime()+windowDays*86400000).toISOString();const deadlines=await this.repository.listDueDeadlines(context.tenantId,before);const created:ReminderProps[]=[];for(const deadline of deadlines){if(await this.repository.hasReminder(context.tenantId,deadline.id,windowDays))continue;const reminder:ReminderProps={id:newEntityId(),tenantId:context.tenantId,deadlineId:deadline.id,customerId,channel,windowDays,scheduledFor:this.now().toISOString(),status:"pending",createdAt:this.now().toISOString()};await this.repository.saveReminder(reminder);created.push(reminder);}return created;}
}
